const W={en:{title:"PMO Dashboard",tab:"Major Sector Projects",overview:"Portfolio overview",total:"Total projects",avg:"Average actual completion",risks:"Projects with risks",search:"Search by project, code or department…",all:"All departments",add:"Add project",strategic:"Strategic initiatives",operational:"Operational projects",actualCompletion:"Actual completion",plannedCompletion:"Planned completion",actualImplementation:"Actual implementation",plannedImplementation:"Planned implementation",actualOperation:"Actual operation",plannedOperation:"Planned operation",achievements:"Achievements",next:"Next steps",challenges:"Challenges & risks",support:"Support needed",edit:"Edit",del:"Delete",code:"Project code",deptCode:"Department code",cancel:"Cancel",save:"Save project",new:"Add new project",editing:"Edit project",empty:"No projects match your filters.",confirm:"Delete this project? This cannot be undone."},ar:{title:"لوحة مكتب إدارة المشاريع",tab:"مشاريع القطاع الرئيسية",overview:"نظرة عامة على المحفظة",total:"إجمالي المشاريع",avg:"متوسط الإنجاز الفعلي",risks:"مشاريع ذات مخاطر",search:"البحث باسم المشروع أو الرمز أو الإدارة…",all:"جميع الإدارات",add:"إضافة مشروع",strategic:"المبادرات الاستراتيجية",operational:"المشاريع التشغيلية",actualCompletion:"الإنجاز الفعلي",plannedCompletion:"الإنجاز المخطط",actualImplementation:"التنفيذ الفعلي",plannedImplementation:"التنفيذ المخطط",actualOperation:"التشغيل الفعلي",plannedOperation:"التشغيل المخطط",achievements:"الإنجازات",next:"الخطوات القادمة",challenges:"التحديات والمخاطر",support:"الدعم المطلوب",edit:"تعديل",del:"حذف",code:"رمز المشروع",deptCode:"رمز الإدارة",cancel:"إلغاء",save:"حفظ المشروع",new:"إضافة مشروع جديد",editing:"تعديل المشروع",empty:"لا توجد مشاريع مطابقة.",confirm:"هل تريد حذف هذا المشروع؟ لا يمكن التراجع."}};
let lang="en",projects=[],editing=null,pendingDelete=null;const $=s=>document.querySelector(s),local=(p,f)=>p[f+(lang==="en"?"En":"Ar")];
function installManagerFields(){const firstFieldset=$("#projectForm fieldset");firstFieldset.insertAdjacentHTML("beforebegin",'<label><span id="managerNameLabel">Project manager name</span><input name="projectManagerName"></label><label><span id="managerEmailLabel">Project manager email</span><input type="email" name="projectManagerEmail"></label>')}
installManagerFields();
async function load(){projects=(await(await fetch("/api/projects")).json()).projects;render()}
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i]").forEach(e=>e.textContent=W[lang][e.dataset.i]);document.querySelectorAll("[data-ph]").forEach(e=>e.placeholder=W[lang][e.dataset.ph]);$("#managerNameLabel").textContent=lang==="en"?"Project manager name":"اسم مدير المشروع";$("#managerEmailLabel").textContent=lang==="en"?"Project manager email":"البريد الإلكتروني لمدير المشروع";$("#brandTitle").textContent=W[lang].title;$("#langBtn").textContent=lang==="en"?"العربية":"English";render()}
function render(){const q=$("#search").value.toLowerCase(),dep=$("#department").value;$("#total").textContent=$("#navCount").textContent=projects.length;$("#average").textContent=(projects.length?Math.round(projects.reduce((s,p)=>s+p.actualCompletionRate,0)/projects.length):0)+"%";$("#riskCount").textContent=projects.filter(p=>p.challengesRisksEn||p.challengesRisksAr).length;const old=dep,$d=$("#department");$d.innerHTML=`<option value="all">${W[lang].all}</option>`;[...new Map(projects.map(p=>[p.departmentCode,local(p,"departmentName")])).entries()].forEach(([c,n])=>$d.insertAdjacentHTML("beforeend",`<option value="${safe(c)}">${safe(n)}</option>`));$d.value=[...$d.options].some(o=>o.value===old)?old:"all";const list=projects.filter(p=>($d.value==="all"||p.departmentCode===$d.value)&&Object.values(p).join(" ").toLowerCase().includes(q));$("#projects").innerHTML=list.length?list.map(card).join(""):`<div class="empty">${W[lang].empty}</div>`}
function safe(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function card(p){return `<article class="card summary" role="link" tabindex="0" onclick="window.open('detail.html?id=${p.id}&lang=${lang}','_blank')" onkeydown="if(event.key==='Enter'||event.key===' ')window.open('detail.html?id=${p.id}&lang=${lang}','_blank')"><div class="card-head"><div><div class="codes"><span>${safe(p.projectCode)}</span><span>${safe(p.departmentCode)}</span></div><h2>${safe(local(p,"projectName"))}</h2><p>${safe(local(p,"departmentName"))}</p></div>${completionCircle(p.actualCompletionRate,W[lang].actualCompletion)}</div><footer><span class="open-detail">${lang==="en"?"Open project details ↗":"فتح تفاصيل المشروع ↗"}</span><button class="history-link" onclick="event.stopPropagation();window.open('history.html?projectCode=${encodeURIComponent(p.projectCode)}&lang=${lang}','_blank')">↺ ${lang==="en"?"History log":"سجل التاريخ"}</button><button class="danger" onclick="event.stopPropagation();askDelete(${p.id})">⌫ ${W[lang].del}</button></footer></article>`}
function completionCircle(rate,label){const tone=rate<50?"rate-red":rate<80?"rate-orange":"rate-green";return `<div class="project-completion ${tone}"><div class="completion-circle" style="--rate:${rate*3.6}deg"><strong>${rate}%</strong></div><span>${label}</span></div>`}
function syncRateValues(source){["actualCompletion","plannedCompletion","actualImplementation","plannedImplementation","actualOperation","plannedOperation"].forEach(k=>$("#"+k+"Value").textContent=(source[k+"Rate"]||0)+"%")}
function openAdd(){editing=null;$("#projectForm").reset();syncRateValues({});$("#formMode").textContent=W[lang].new;$("#overlay").classList.remove("hidden")}
function openEdit(id){editing=projects.find(p=>p.id===id);for(const [k,v] of Object.entries(editing))if($("#projectForm").elements[k])$("#projectForm").elements[k].value=v;syncRateValues(editing);$("#formMode").textContent=W[lang].editing;$("#overlay").classList.remove("hidden")}
function askDelete(id){pendingDelete=id;$("#deleteOverlay").classList.remove("hidden")}async function removeProject(){if(pendingDelete===null)return;await fetch(`/api/projects/${pendingDelete}`,{method:"DELETE"});pendingDelete=null;$("#deleteOverlay").classList.add("hidden");load()}
$("#projectForm").onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));["actualCompletionRate","plannedCompletionRate","actualImplementationRate","plannedImplementationRate","actualOperationRate","plannedOperationRate"].forEach(k=>body[k]=Number(body[k]));await fetch(editing?`/api/projects/${editing.id}`:"/api/projects",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});closeModal();load()};
function closeModal(){$("#overlay").classList.add("hidden")}$("#addBtn").onclick=openAdd;$("#closeBtn").onclick=$("#cancelBtn").onclick=closeModal;$("#langBtn").onclick=()=>{lang=lang==="en"?"ar":"en";translate()};$("#search").oninput=render;$("#department").onchange=render;["actualCompletion","plannedCompletion","actualImplementation","plannedImplementation","actualOperation","plannedOperation"].forEach(k=>$("#projectForm").elements[k+"Rate"].oninput=e=>$("#"+k+"Value").textContent=e.target.value+"%");$("#deleteCancel").onclick=()=>{$("#deleteOverlay").classList.add("hidden");pendingDelete=null};$("#deleteConfirm").onclick=removeProject;load();
