const q=new URLSearchParams(location.search),projectCode=q.get("projectCode")||"",$=s=>document.querySelector(s);let lang=q.get("lang")==="ar"?"ar":"en",logs=[],pendingDelete=null,replyingId=null,editingId=null;
const T={en:{dashboard:"PMO Dashboard",title:"Project history log",newLog:"Add history record",text:"Log text",user:"User",save:"Save record",saving:"Saving…",empty:"No history records for this project.",noMatch:"No history records match your search.",error:"The history record could not be saved.",delete:"Delete",deleteTitle:"Delete Confirmation",deleteMessage:"Are you sure you want to delete this entry?",cancel:"Cancel",search:"Search log text or user",searchPlaceholder:"Enter text or user name…",date:"Record date",clear:"Clear",reply:"Reply",replyLabel:"Reply to this entry",replyPlaceholder:"Enter your reply…",saveReply:"Save reply",edit:"Edit",editLabel:"Edit log text",saveChanges:"Save changes"},ar:{dashboard:"لوحة مكتب إدارة المشاريع",title:"سجل تاريخ المشروع",newLog:"إضافة سجل جديد",text:"نص السجل",user:"المستخدم",save:"حفظ السجل",saving:"جارٍ الحفظ…",empty:"لا توجد سجلات لهذا المشروع.",noMatch:"لا توجد سجلات مطابقة للبحث.",error:"تعذر حفظ سجل التاريخ.",delete:"حذف",deleteTitle:"تأكيد الحذف",deleteMessage:"هل أنت متأكد من رغبتك في حذف هذا السجل؟",cancel:"إلغاء",search:"البحث في نص السجل أو المستخدم",searchPlaceholder:"أدخل النص أو اسم المستخدم…",date:"تاريخ السجل",clear:"مسح",reply:"رد",replyLabel:"الرد على هذا السجل",replyPlaceholder:"أدخل ردك…",saveReply:"حفظ الرد",edit:"تعديل",editLabel:"تعديل نص السجل",saveChanges:"حفظ التغييرات"}};
function safe(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function localDate(timestamp){const d=new Date(timestamp);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function filteredLogs(){const text=$("#historySearch").value.trim().toLowerCase(),date=$("#historyDate").value;return logs.filter(x=>`${x.logText} ${x.user}`.toLowerCase().includes(text)&&(!date||localDate(x.timestamp)===date))}
function show(){const t=T[lang],filtered=filteredLogs();document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";$("#brandTitle").textContent=t.dashboard;$("#langBtn").textContent=lang==="en"?"العربية":"English";$("#historyTitle").textContent=t.title;$("#newLogTitle").textContent=t.newLog;$("#logTextLabel").textContent=t.text;$("#userLabel").textContent=t.user;$("#saveLog").textContent=t.save;$("#projectCode").textContent=projectCode;$("#historySearchLabel").textContent=t.search;$("#historySearch").placeholder=t.searchPlaceholder;$("#historyDateLabel").textContent=t.date;$("#historyClear").textContent=t.clear;$("#historyDeleteTitle").textContent=t.deleteTitle;$("#historyDeleteMessage").textContent=t.deleteMessage;$("#historyDeleteCancel").textContent=t.cancel;$("#historyDeleteConfirm").textContent=t.delete;$("#historyList").innerHTML=!logs.length?`<div class="history-empty">${t.empty}</div>`:!filtered.length?`<div class="history-empty">${t.noMatch}</div>`:filtered.map(x=>`<article><div class="history-meta"><strong>${safe(x.user)}</strong><time>${new Intl.DateTimeFormat(lang==="en"?"en-GB":"ar-QA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x.timestamp))}</time></div><p>${safe(x.logText)}</p><div class="history-entry-actions"><button class="history-edit" onclick="openEdit(${x.id})">✎ ${t.edit}</button><button class="history-reply" onclick="openReply(${x.id})">↩ ${t.reply}</button><button class="history-delete" onclick="askDelete(${x.id})">⌫ ${t.delete}</button></div>${editingId===x.id?`<form class="history-reply-form" onsubmit="saveEdit(event,${x.id})"><label>${t.editLabel}<textarea id="editText-${x.id}" required autofocus>${safe(x.logText)}</textarea></label><div><button type="button" onclick="closeEdit()">${t.cancel}</button><button class="primary" type="submit">${t.saveChanges}</button></div></form>`:""}${replyingId===x.id?`<form class="history-reply-form" onsubmit="saveReply(event,${x.id})"><label>${t.replyLabel}<textarea id="replyText-${x.id}" required autofocus placeholder="${t.replyPlaceholder}"></textarea></label><div><button type="button" onclick="closeReply()">${t.cancel}</button><button class="primary" type="submit">${t.saveReply}</button></div></form>`:""}</article>`).join("");const activeId=editingId??replyingId;if(activeId!==null){const field=$(editingId!==null?`#editText-${activeId}`:`#replyText-${activeId}`);if(field)field.focus()}}
async function load(){const r=await fetch(`/api/history/${encodeURIComponent(projectCode)}`);logs=r.ok?(await r.json()).logs:[];show()}
function askDelete(id){pendingDelete=id;$("#historyDeleteOverlay").classList.remove("hidden")}
function closeDelete(){pendingDelete=null;$("#historyDeleteOverlay").classList.add("hidden")}
function openReply(id){replyingId=id;editingId=null;show()}
function closeReply(){replyingId=null;show()}
function openEdit(id){editingId=id;replyingId=null;show()}
function closeEdit(){editingId=null;show()}
async function saveEdit(e,id){e.preventDefault();const field=$(`#editText-${id}`),button=e.target.querySelector("button[type=submit]"),logText=field.value.trim();if(!logText)return;button.disabled=true;button.textContent=T[lang].saving;const r=await fetch(`/api/history/${encodeURIComponent(projectCode)}/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({logText})});if(r.ok){editingId=null;await load()}else{button.disabled=false;button.textContent=T[lang].saveChanges}}
async function saveReply(e,id){e.preventDefault();const field=$(`#replyText-${id}`),button=e.target.querySelector("button[type=submit]"),replyText=field.value.trim();if(!replyText)return;button.disabled=true;button.textContent=T[lang].saving;const r=await fetch(`/api/history/${encodeURIComponent(projectCode)}/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({replyText})});if(r.ok){replyingId=null;await load()}else{button.disabled=false;button.textContent=T[lang].saveReply}}
async function deleteEntry(){if(pendingDelete===null)return;const r=await fetch(`/api/history/${encodeURIComponent(projectCode)}/${pendingDelete}`,{method:"DELETE"});if(r.ok){closeDelete();await load()}}
$("#historyForm").onsubmit=async e=>{e.preventDefault();const button=$("#saveLog"),body=Object.fromEntries(new FormData(e.target));button.disabled=true;button.textContent=T[lang].saving;$("#historyError").textContent="";const r=await fetch(`/api/history/${encodeURIComponent(projectCode)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(r.ok){e.target.elements.logText.value="";await load()}else $("#historyError").textContent=(await r.json()).error||T[lang].error;button.disabled=false;button.textContent=T[lang].save};
$("#langBtn").onclick=()=>{lang=lang==="en"?"ar":"en";show()};$("#historySearch").oninput=show;$("#historyDate").onchange=show;$("#historyClear").onclick=()=>{$("#historySearch").value="";$("#historyDate").value="";show()};$("#historyDeleteCancel").onclick=closeDelete;$("#historyDeleteConfirm").onclick=deleteEntry;load();
